[package]
name = "rs-sql-indent"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A CLI tool that formats SQL from stdin"

[dependencies]
clap = { version = "4", features = ["derive"] }
sqlformat = "0.2"
